export const dealerConstants = {
    DEALERLIST_REQUEST: "DEALERLIST_REQUEST",
    DEALERLIST_SUCCESS: "DEALERLIST_SUCCESS",
    DEALERLIST_FAILURE: "DEALERLIST_FAILURE",
  };
  
  export const ratingConstants = {
    RATING_LIST_REQUEST: "RATING_LIST_REQUEST",
    RATING_LIST_SUCCESS: "RATING_LIST_SUCCESS",
    RATING_LIST_FAILURE: "RATING_LIST_FAILURE",
  };
  
  export const ratingFilterConstants = {
    RATING_FILTER_REQUEST: "RATING_FILTER_REQUEST",
    RATING_FILTER_SUCCESS: "RATING_FILTER_SUCCESS",
    RATING_FILTER_FAILURE: "RATING_FILTER_FAILURE",
  };

  
  export const salesUserConstants = {
    SALES_GET_REQUEST: "SALES_GET_REQUEST",
    SALES_GET_SUCCESS: "SALES_GET_SUCCESS",
    SALES_GET_FAILURE: "SALES_GET_FAILURE",
  };